# Generated by Django 4.2.4 on 2023-09-04 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquemovimento',
            name='emprestimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.emprestimo'),
        ),
        migrations.AddField(
            model_name='estoquemovimento',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='estoquemovimento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Entrada'), (2, 'Saída')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, 'O CPF deve conter obrigatóriamente 11 digitos')], verbose_name='CPF sem . e -'),
        ),
        migrations.CreateModel(
            name='EntradaLivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
            ],
        ),
    ]
