# Generated by Django 4.2.4 on 2023-09-04 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_estoquemovimento_emprestimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquemovimento',
            name='entrada_livros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.entradalivros'),
        ),
    ]
